/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'marc' at '20/01/17 18:00' with Gradle 3.0
 *
 * @author marc, @date 20/01/17 18:00
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
