/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'marc' at '20/01/17 18:00' with Gradle 3.0
 *
 * @author marc, @date 20/01/17 18:00
 */

import spock.lang.Specification

class LibraryTest extends Specification {
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
